version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./projects.db:/app/projects.db
      - ./static/images:/app/static/images
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
